### ISSUE TITLE
Node instance IAM role removed from aws-auth configmap upon updating KubernetesApiAccess on existing cluster

### ISSUE THREAD

**Issue by seanjoo** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#17]
If the KubernetesApiAccess property is changed on an existing cluster that has node groups, the aws-auth configmap does not retain the node instance roles.

**Comment by niemyjski** [comment]
This happens if you update anything on the cluster (`AWSQS::EKS::Cluster`) through CloudFormation. It seems that when the `AWSQS::EKS::Cluster` resource is triggered for any update, it replaces the auth-map with a json version (original was yaml). It drops the two system default entries that were added automatically on creation (shown below). 

**After this occurs the nodes can no communicate with the control plane/cluster. This causes the cluster to degrade**

```yaml
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-elasticsearchNodeRole-Z1YMO0ZPBNV4
  username: system:node:{{EC2PrivateDNSName}}
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-appNodeRole-W16BEVL93WZY
  username: system:node:{{EC2PrivateDNSName}}
```
When any update occurs the `aws-auth` config maps `mapRoles` value is converted to json and only our defined roles in the cloud formation files are present (the two generated above are not included).

## Original
```yaml

```yaml
- groups:
  - aws-auth-admin
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-activations-eksClusterExtensionRole-IMC1JLKY7V00
- groups:
  - aws-auth-admin
  rolearn: arn:aws:iam::xxxxxxx:role/CloudFormation-Kubernetes-VPC
- groups:
  - system:masters
  rolearn: arn:aws:iam::xxxxxxx:role/OrganizationAccountAccessRole
  username: AdminRole
- groups:
  - system:masters
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-activations-helmExtensionRole-XSYLCPFXD6H
  username: HelmExtensionRole
- groups:
  - system:masters
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-activations-k8sResourceExtensionRole-17HTR4JX5N196
  username: ResourceExtensionRole
- groups:
  - system:masters
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-appNodeRole-W16BEVL93WZY
- groups:
  - system:masters
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-elasticsearchNodeRole-Z1YMO0ZPBNV4
- groups:
  - system:masters
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-kubeCtlRole-58W2X9Y59D6A
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-elasticsearchNodeRole-Z1YMO0ZPBNV4
  username: system:node:{{EC2PrivateDNSName}}
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-appNodeRole-W16BEVL93WZY
  username: system:node:{{EC2PrivateDNSName}}
```

After updating

```json
[
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-activations-eksClusterExtensionRole-IMC1JLKY7V00",
        "groups": [
            "aws-auth-admin"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/CloudFormation-Kubernetes-VPC",
        "groups": [
            "aws-auth-admin"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/OrganizationAccountAccessRole",
        "username": "AdminRole",
        "groups": [
            "system:masters"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-activations-helmExtensionRole-XSYLCPFXD6H",
        "username": "HelmExtensionRole",
        "groups": [
            "system:masters"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-activations-k8sResourceExtensionRole-17HTR4JX5N196",
        "username": "ResourceExtensionRole",
        "groups": [
            "system:masters"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-appNodeRole-W16BEVL93WZY",
        "username": "NodeRole",
        "groups": [
            "system:masters"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-elasticsearchNodeRole-Z1YMO0ZPBNV4",
        "username": "NodeRole",
        "groups": [
            "system:masters"
        ]
    },
    {
        "rolearn": "arn:aws:iam::xxxxxxx:role/xxxxxxx-eks-cluster-kubeCtlRole-58W2X9Y59D6A",
        "username": "KubeCtlAdmin",
        "groups": [
            "system:masters"
        ]
    }
]
```

cc @jaymccon @troy-ameigh can we please get some help with this, this is making the cluster un-trustable/usable.

**Comment by niemyjski** [comment]
![image](https://user-images.githubusercontent.com/1020579/150607390-9a80235d-ada4-439f-95ac-8202475e5f05.png)

Changing the node role username and groups seemed to resolve this issue. It would be really good to include this in the docs.

**Comment by andre-lx** [comment]
Thanks @niemyjski I fixed this adding to the KubernetesApiAccess the missing role:

```yaml
KubernetesApiAccess:
  Roles:
  # nodeRole so the ec2 instances are able to connect to the k8s master
  - Arn: !GetAtt EKSNodeGroupsRole.Arn
    Username: system:node:{{EC2PrivateDNSName}}
    Groups:
    - system:bootstrappers
    - system:nodes
```

**Comment by timrichardson** [comment]
I am new user but I think I have this problem. Could some one provide tips at a beginner level to fix this? That is, I do not know how to edit missing roles.

**Comment by andre-lx** [comment]
Hi @timrichardson. 

Sorry but I didn't understand the question.

It is literally copy and paste my comment above. 

In the cluster properties like:

```yaml
  EKSCluster:
    Type: AWSQS::EKS::Cluster
    Properties:
      KubernetesApiAccess:
        Roles:
        # nodeRole so the ec2 instances are able to connect to the k8s master
        - Arn: !GetAtt EKSNodeGroupsRole.Arn
          Username: {% raw %}system:node:{{EC2PrivateDNSName}}{% endraw %}
          Groups:
          - system:bootstrappers
          - system:nodes
```

**Comment by timrichardson** [comment]
If I do kubectl edit -n kube-system configmap/aws-auth
then I see:

```
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group
      rolearn: arn:aws:iam::xxx:role/eksctl-django-api-sync-nodegroup-NodeInstanceRole-1TYYBMUH6LFLX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - cluster-admin
      rolearn: arn:aws:iam::xxx:role/admin
  mapUsers: |
    - groups:
      - cluster-admin
      - eks-console-dashboard-full-access-group
      userarn: arn:aws:iam::xxx:user/api_super_user
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-22T02:32:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2602340"
  uid: 53afcd8b-3bc1-43e7-ba7d-a7bf33371bb2
```
~                              
Perhaps my problem is different. Yesterday I tried to understand why my AWS root account couldn't access the cluster and I experimented with aws-auth

**Comment by andre-lx** [comment]
This part is automatically added on creation time. 

The problem is that with updates, this part is deleted (since the extension makes a replacement in the aws-auth configmap), so the ec2 don't have access to the k8s master any more.

```yaml
    - groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group
      rolearn: arn:aws:iam::xxx:role/eksctl-django-api-sync-nodegroup-NodeInstanceRole-1TYYBMUH6LFLX
      username: system:node:{{EC2PrivateDNSName}}
```

Adding this to the CF template, will add this in creation and the updates, so the problem disappears.
