### ISSUE TITLE
A hard coded role "CloudFormation-Kubernetes-VPC" created internally

### ISSUE THREAD

**Issue by jineshmathewt** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#22]
When I am using this quick start project to create the EKS cluster of type "AWSQS::EKS::Cluster" it internally creates a IAM Role "CloudFormation-Kubernetes-VPC" if it is not already present. In my project all IAM roles follows certain naming convention and it doesn't allow to create a IAM role with name "CloudFormation-Kubernetes-VPC". 

Is there a way to skip this role creation or is there a way to specify an IAM role with different name?

In iam.go
----------
const (
	**iamRoleName**      = "CloudFormation-Kubernetes-VPC"
	lambdaAssumeRole = `{
		  "Version": "2012-10-17",
		  "Statement": [
			{
			  "Effect": "Allow",
			  "Principal": {
				"Service": "lambda.amazonaws.com"
			  },
			  "Action": "sts:AssumeRole"
			}
		  ]
		}`
)

func getRole(svc iamiface.IAMAPI) (*string, *string, error) {
	input := &iam.GetRoleInput{
		RoleName: aws.String(**iamRoleName**),
	}
	output, err := svc.GetRole(input)
	if err != nil {
		return nil, nil, err
	}
	return output.Role.RoleName, output.Role.Arn, nil
}

**Comment by owenthereal** [comment]
Please make this configurable. I just ran into the issue.

**Comment by owenthereal** [comment]
Looking at https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider/blob/0363b1d115c6b44970706f14a9ccef1d0dd73015/cmd/resource/k8sauth.go#L150. Should we use the passed in `LambdaRoleName` there instead of the hardcoded `CloudFormation-Kubernetes-VPC` in that line?

**Comment by xor007** [comment]
I am running the sample template now and this role did not create for me.

**Comment by andre-lx** [comment]
yes it is possible to ignore the CloudFormation-Kubernetes-VPC role creation and use a custom one:

```yaml
  AWSQSVPCProxyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'AWSQSLambdaIAMRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
      - Key: Name
        Value: 'AWSQSLambdaIAMRole'

  EKSCluster:
    Type: AWSQS::EKS::Cluster
    Properties:
      Name:  'cluster'
      LambdaRoleName: !Ref AWSQSVPCProxyRole
      .
      .
      .
      .
```
