### ISSUE TITLE
Using few stacks with activation exstension

### ISSUE THREAD

**Issue by greenhua** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#44]
I am sorry, possible my question is offtopic, but related with project 

I am trying to use CloudFormation with extensions

```
EKSClusterExtension:
    Type: AWS::CloudFormation::TypeActivation
    Properties:
      AutoUpdate: false
      TypeNameAlias:  !Sub "EKS::Cluster::${EnvironmentName}"
     
  EKS:
    Type: !Sub "EKS::Cluster::${EnvironmentName}"
    Properties:
      Name: !Ref EnvironmentName
      RoleArn: !GetAtt Kubernetes.Arn
```

and have error message:

`Template format error: [/Resources/EKS] Every Type member must be a string.
`
How can i resolve this error?
