### ISSUE TITLE
Support creating clusters that are private on creation

### ISSUE THREAD

**Issue by JordanDeBeer** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#5]
Currently, this resource provider works by creating a cluster with the public endpoint enabled and later resolving to the endpoint configuration defined in the template.  For example, a resource with the following config:

```
  SampleEKSCluster:
    Type: AWSQS::EKS::Cluster
    Properties:
      Name: MyCluster
      RoleArn: arn:aws:iam::1234567890:role/eksClusterRole
      KubernetesApiAccess:
        Roles:
          - Arn: !Ref RoleArn
            Username: !Ref Username
            Groups: ["system:masters"]
      ResourcesVpcConfig:
        EndpointPrivateAccess: true
        EndpointPublicAccess: false
        SecurityGroupIds: !Ref SecurityGroups
        SubnetIds: !Ref Subnets
```

Would go through a lifecycle where; the cluster is created with the public endpoint enabled, then the auth-config is updated to allow the declared Role access, then the cluster is set to private.

The lambda function that updates the auth-config is created in the same subnet(s) and security group(s) as the cluster, so creating a cluster that is initially private should be possible.
