### ISSUE TITLE
Helm Resouce stopped working

### ISSUE THREAD

**Issue by danielc-salt** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#54]
For some reason the resource stopped working in without any changes, error is:
"Error: At Helm install - Kubernetes cluster unreachable: the server has asked for the client to provide credentials "
My Cluster has the following permission that used to work:
```
      Type: 'AWSQS::EKS::Cluster'
      KubernetesApiAccess:
        Roles:
          - Arn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${whoami}"
            Username: "AdminRole"
            Groups: ["system:masters"]
          - Arn: !GetAtt NodeInstanceRole.Arn
            Username: "system:node:{{EC2PrivateDNSName}}"
            Groups: ["system:bootstrappers","system:nodes"]
```
It was working before the holidays!
On the authentication log of the cluster I see this entry:
time="2023-01-07T21:44:03Z" level=warning msg="access denied" arn="arn:aws:iam::111111111111:role/CloudFormation-EKS-HelmDeploy-us-east-1" client="127.0.0.1:44610" error="ARN is not mapped" method=POST path=/authenticate

Clues?
