### ISSUE TITLE
Pre built package

### ISSUE THREAD

**Issue by andre-lx** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#65]
Can you please provide the built zip for version 1.13.0? 

We have the zip on the helm resource but not for this one.

This will be a lot easier to us to continue using this. 

Thanks

**Comment by andre-lx** [comment]
If you come across this, you can enable the extension using the following CF template.

If you enabled the extension manually, you will need to disable it first (so we don't have duplications on the resource type name). 
If you enabled the extension via CF, you will need to delete the stack of the extension before running this one, otherwise, the TypeActivation deletion will fail. 

Just upload this to your s3, and replace the bucket at the `AWSQSEKSClusterResourceVersion`
[awsqs-eks-cluster.zip](https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider/files/11311023/awsqs-eks-cluster.zip)

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Extensions
Resources:
  # AWSQS::EKS::Cluster
  AWSQSEKSClusterExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - 'AWSQSExecutionIAMRole'
          - !Select [2, !Split [ '/', !Ref AWS::StackId ]]
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - resources.cloudformation.amazonaws.com
            - cloudformation.amazonaws.com
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: !Join
          - '-'
          - - 'AWSQSExecutionIAMRole'
            - 'policy'
            - !Select [2, !Split [ '/', !Ref AWS::StackId ]]
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sts:GetCallerIdentity
            - eks:CreateCluster
            - eks:DeleteCluster
            - eks:DescribeCluster
            - eks:ListTagsForResource
            - eks:UpdateClusterVersion
            - eks:UpdateClusterConfig
            - eks:TagResource
            - eks:UntagResource
            - lambda:UpdateFunctionConfiguration
            - lambda:DeleteFunction
            - lambda:GetFunction
            - lambda:InvokeFunction
            - lambda:CreateFunction
            - lambda:UpdateFunctionCode
            - ec2:DescribeVpcs
            - ec2:DescribeSubnets
            - ec2:DescribeSecurityGroups
            - kms:CreateGrant
            - kms:DescribeKey
            Resource:
            - '*'
          - Effect: Allow
            Action:
            - iam:PassRole
            Resource:
            - !Sub arn:aws:iam::${AWS::AccountId}:role/*
            Condition:
              StringEquals:
                iam:PassedToService:
                - eks.amazonaws.com
                - lambda.amazonaws.com
              StringLike:
                iam:AssociatedResourceArn:
                - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*
                - !Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/*
      Tags:
      - Key: Name
        Value: !Join
          - '-'
          - - 'AWSQSExecutionIAMRole'
            - !Select [2, !Split [ '/', !Ref AWS::StackId ]]

  AWSQSEKSClusterLogDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - 'AWSQSLogDeliveryIAMRole'
          - !Select [2, !Split [ '/', !Ref AWS::StackId ]]
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - resources.cloudformation.amazonaws.com
            - cloudformation.amazonaws.com
          Action: sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: !Join
          - '-'
          - - 'AWSQSLogDeliveryIAMRole'
            - 'policy'
            - !Select [2, !Split [ '/', !Ref AWS::StackId ]]
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - cloudwatch:ListMetrics
            - cloudwatch:PutMetricData
            Resource:
            - '*'
      Tags:
      - Key: Name
        Value: !Join
          - '-'
          - - 'AWSQSLogDeliveryIAMRole'
            - !Select [2, !Split [ '/', !Ref AWS::StackId ]]

  AWSQSEKSClusterResourceVersion:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      TypeName: AWSQS::EKS::Cluster
      ExecutionRoleArn: !GetAtt AWSQSEKSClusterExecutionRole.Arn
      LoggingConfig:
        LogGroupName: !Join
          - '-'
          - - '/aws/cloudformation/registry/AWSQSEKSClusterLogGroup'
            - !Select [2, !Split [ '/', !Ref AWS::StackId ]]
        LogRoleArn: !GetAtt AWSQSEKSClusterLogDeliveryRole.Arn
      SchemaHandlerPackage: s3://YOUR_BUCKET/awsqs_eks_cluster/awsqs-eks-cluster.zip

  AWSQSEKSClusterResourceDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeVersionArn: !Ref AWSQSEKSClusterResourceVersion
```
