### ISSUE TITLE
The life cycle for updating EKS control plane external access IP policy not work.

### ISSUE THREAD

**Issue by yuriifurko** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#7]
I receive an issue when I trying to add or removing the IP address from the list. 
Remote access without Bastion is very important for the Test/Dev stage. 
It will be very good if we can fix it.

My CloudFormation Template look as:
```
Parameters
  EKSPublicAccessCIDRs:
    Type: List<String>
    Default:  1.2.3.4/32, 5.6.7.8/32

  EKSControlPlane:
    Type: AWSQS::EKS::Cluster
    Properties:
        PublicAccessCidrs: !Ref EKSPublicAccessCIDRs
        EndpointPrivateAccess: !If [ EnablePrivateEndpoint, true, false ]
        EndpointPublicAccess: !If [ EnablePublicEndpoint, true, false ]

```
Issue Reasons:

`[Error] Put "https://XXXXXXXXXXXXXXXXXXXX.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 172.16.10.44:443: i/o timeout
`

Thank you for advance.
